# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    # copy web.config to dist dir
    - run: cp "wwwroot/web.config" "dist/angular-first-project/web.config"
    
    - name: List Files in Distribution Directory
      run: ls -R ./dist/angular-first-project

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "${{ secrets.FTP_SERVER }}"
        username: "${{ secrets.FTP_USER }}"
        password: "${{ secrets.FTP_PASSWORD }}"
        local-dir: "dist/angular-first-project/"
        server-dir: "/"
